# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ../../../src/server/downloadprogress.h \
    ../../../src/server/updaterservermanager.h \
    ../../../src/ClientCenter.h \
    ../../../../include/CommonFileOperFunction.h \
    ../../../../include/CommonFtpOperFunction.h \
    ../../../../include/global.h \
    ../../../include/IClientCenter.h \
    ../../../../include/MD5.h \
    ../../../../include/pubfuncs.h \
    ../../../../include/WexTextCodecPlugin.h \
    ../../../../include/WindowPos.h \
    ../../../include/IUpdateXmlPlist.h \
    ../../../src/UpdateXmlPlist.h \
    ../../../../include/FtpThread.h \
    ../../../../include/PlatformFunctions.h

#Source files
SOURCES += ../../../src/server/downloadprogress.cpp \
    ../../../src/server/main.cpp \
    ../../../src/server/updaterservermanager.cpp \
    ../../../src/ClientCenter.cpp \
    ../../../../source/MD5.cpp \
    ../../../../source/WexTextCodecPlugin.cpp \
    ../../../src/UpdateXmlPlist.cpp \
    ../../../../source/FtpThread.cpp

#Forms
FORMS += ./downloadprogress.ui \
    ./updaterservermanager.ui

#Resource file(s)
RESOURCES += ./updaterservermanager.qrc
