# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ../../../include/ApplicationSington.h \
    ../../../src/ClientCenter.h \
    ../../../../include/CommonFileOperFunction.h \
    ../../../../include/CommonFtpOperFunction.h \
    ../../../src/dataFromFile.h \
    ../../../../include/global.h \
    ../../../../include/MD5.h \
    ../../../include/PlatformFunctions.h \
    ../../../../include/pubfuncs.h \
    ../../../../include/TrayWindow.h \
    ../../../src/UpdateXmlPlist.h \
    ../../../../include/WexTextCodecPlugin.h \
    ../../../../include/WindowPos.h \
    ../../../src/client/aboutdlg.h \
    ../../../src/client/dataFromFile.h \
    ../../../src/client/downloadprogress.h \
    ../../../src/client/InstallThread.h \
    ../../../src/client/updaterclient.h \
    ../../../include/IClientCenter.h \
    ../../../include/IUpdateXmlPlist.h

#Source files
SOURCES += ../../../src/ClientCenter.cpp \
    ../../../../source/MD5.cpp \
    ../../../../source/TrayWindow.cpp \
    ../../../src/UpdateXmlPlist.cpp \
    ../../../../source/WexTextCodecPlugin.cpp \
    ../../../src/client/aboutdlg.cpp \
    ../../../src/client/downloadprogress.cpp \
    ../../../src/client/InstallThread.cpp \
    ../../../src/client/main.cpp \
    ../../../src/client/updaterclient.cpp

#Forms
FORMS += ./aboutdlg.ui \
    ./downloadprogress.ui \
    ./updaterclient.ui

#Resource file(s)
RESOURCES += ../../../resource/updaterclient.qrc
